spring.application.name=news
spring.datasource.url=jdbc:postgresql://localhost:15432/news
spring.datasource.username=admin
spring.datasource.password=abc123
spring.jpa.show-sql=true


spring.flyway.locations=classpath:/db/migration
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ninja.hau1@gmail.com
spring.mail.password=oxyakxiacqwbmwvb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

nytimes.api.key=1wFZncc9sJF7FWGauLpWSkhkCPurhUtz2qzxrP3zAGUN29nw
nytimes.api.base-url=https://api.nytimes.com/svc/topstories/v2/



